name: video_compressor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  file_selector: ^0.9.2+2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  video_player: ^2.4.8
  syncfusion_flutter_sliders: ^20.3.58
  get_storage: ^2.0.3
  # ffmpeg_kit_flutter: ^5.1.0
  share_extend: ^2.0.0
  ffmpeg_kit_flutter_full_gpl: ^5.1.0-LTS
  url_launcher: ^6.1.7
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  
flutter: 
  uses-material-design: true

